-- Create user table
CREATE TABLE IF NOT EXISTS user (
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

-- Create todo table
CREATE TABLE IF NOT EXISTS todo (
  id INT PRIMARY KEY AUTO_INCREMENT,
  task VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  userId VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES user(id)
);
